name: "MAIN webadmin workflow"
on:
  pull_request:
    branches: ["main"]
  workflow_dispatch:
defaults:
  run:
    working-directory: ./application

jobs:
  build-to-prod:
    name: Build & Push Docker image to Production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: check pwd
        run: ls