#name: "Tag"

on:
  push:
    branches: ["github-"]
  pull_request:
    types:
      - closed
    branches: ["main"]
  workflow_dispatch:

defaults:
  run:
    working-directory: ./application

jobs:
  first_run:
    name: First Run
    runs-on: ubuntu-latest

    steps:
      - name: Docker pull from registry
        run: |
          docker --version
          docker images
  
  image-version:
    name: Image Version
    runs-on: ubuntu-latest
    needs: containerize

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Github SHA
        run: git log -5 #| grep ^commit | cut -d " " -f 2

      - name: Docker pull from registry
        run: |
          docker --version
          docker images
